stages:
  - build
  - test
  - deploy


variables:
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

# --- ÉTAPE DE BUILD & PUSH ---
build_images:
  stage: build
  image: docker:26.1.4
  services:
    - docker:26.1.4-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    # Build & push backend
    - docker build --provenance=false -t "$CI_REGISTRY_IMAGE/backend:$IMAGE_TAG" -f dockerfile_backend .
    - docker push "$CI_REGISTRY_IMAGE/backend:$IMAGE_TAG"
    # Build & push frontend
    - docker build --provenance=false -t "$CI_REGISTRY_IMAGE/frontend:$IMAGE_TAG" -f dockerfile_frontend .
    - docker push "$CI_REGISTRY_IMAGE/frontend:$IMAGE_TAG"


# --- ÉTAPE DE TEST ---
test_images:
  stage: test
  image: docker:26.1.4
  services:
    - docker:26.1.4-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker rm -f test-backend test-frontend 2>/dev/null || true
  script:
    # 1. Récupération des images fraîchement buildées depuis le Registry
    - docker pull "$CI_REGISTRY_IMAGE/backend:$IMAGE_TAG"
    - docker pull "$CI_REGISTRY_IMAGE/frontend:$IMAGE_TAG"
    
    # 2. Test du Backend (Lancement du conteneur + vérification HTTP)
    - docker run -d --name test-backend -p 5000:5000 "$CI_REGISTRY_IMAGE/backend:$IMAGE_TAG"
    - sleep 5
    # Utilisation d'un conteneur avec curl pour tester le backend sur le réseau Docker
    - docker run --network host curlimages/curl:latest http://localhost:5000/ || (docker logs test-backend && exit 1)
    - docker rm -f test-backend

    # 3. Test du Frontend (Lancement du conteneur + vérification HTTP)
    - docker run -d --name test-frontend -p 80:5000 "$CI_REGISTRY_IMAGE/frontend:$IMAGE_TAG"
    - sleep 3
    - docker run --network host curlimages/curl:latest http://localhost:80/ || (docker logs test-frontend && exit 1)
    - docker rm -f test-frontend



# --- ÉTAPE DE DÉPLOIEMENT ---
deploy_uat:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add  openssh-client
    - chmod 400 "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - ssh-keyscan -H "$TARGET_SERVER_IP" >> ~/.ssh/known_hosts
  script:
    # 1. Copie du compose.yml
    - scp -i "$SSH_PRIVATE_KEY" compose.yml "$TARGET_SERVER_USER@$TARGET_SERVER_IP:~/app/compose.yml"
    
    # 2. Connexion SSH avec -i et login explicitement en http://
    - |
      ssh -i "$SSH_PRIVATE_KEY" "$TARGET_SERVER_USER@$TARGET_SERVER_IP" "
        set -e
        cd ~/app
        echo '$CI_REGISTRY_PASSWORD' | docker login -u '$CI_REGISTRY_USER' --password-stdin $CI_REGISTRY
        
        export CI_REGISTRY_IMAGE='$CI_REGISTRY_IMAGE'
        export IMAGE_TAG='$IMAGE_TAG'
        
        docker compose pull
        docker compose up -d --remove-orphans
        docker image prune -f
        docker logout $CI_REGISTRY
      "
  only:
    - main