FROM python:3.12.1-alpine

RUN apk update

WORKDIR /app

COPY ./backend/ /app/

RUN pip install -r requirements.txt

COPY bdd/ ./bdd/

CMD [ "flask", "--app", "backend", "run","--host", "0.0.0.0", "--port", "5000"]